---
- name: Install and Launch Metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: Download metricbeat
    ansible.builtin.command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install metricbeat
    ansible.builtin.command: dpkg -i metricbeat-7.6.1-amd64.deb 

  - name: Copy config file to metricbeat directory
    ansible.builtin.copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure docker module for metricbeat
    ansible.builtin.command: metricbeat modules enable docker

  - name: Setup metricbeat
    ansible.builtin.command: metricbeat setup

  - name: Start metricbeat
    ansible.builtin.command: sudo service metricbeat start

  - name: Enable service metricbeat
    ansible.builtin.systemd:
      name: metricbeat
      enabled: true
