---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
  - name: Install docker.io
    ansible.builtin.apt:
      force_apt_get: true
      update_cache: true
      name: docker.io
      state: present

  - name: Install pip3
    ansible.builtin.apt:
      force_apt_get: true
      name: python3-pip
      state: present

  - name: Install docker
    ansible.builtin.pip:
      name: docker
      state: present

  - name: Stop apache2 if is already running
    ansible.builtin.systemd:
      name: apache2
      state: stopped

  - name: Download and launch dvwa (Damn Vulnerable Web Application)
    community.docker.docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      restart_policy: always
      published_ports: 80:80

  - name: Enable docker service
    ansible.builtin.systemd:
      name: docker
      enabled: true
